-- Création de la table DETAIL_FACTURE si elle n'existe pas
CREATE TABLE IF NOT EXISTS DETAIL_FACTURE (
    ID_DETAIL INT AUTO_INCREMENT PRIMARY KEY,
    ID_FACTURE INT NOT NULL,
    ID_PRODUIT INT NOT NULL,
    QUANTITE INT NOT NULL DEFAULT 1,
    PRIX_UNITAIRE DECIMAL(15, 2) NOT NULL DEFAULT 0,
    FOREIGN KEY (ID_FACTURE) REFERENCES FACTURE(ID_FACTURE) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT)
);

-- Message de confirmation
SELECT 'Table DETAIL_FACTURE créée/vérifiée avec succès' AS message;
